version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "ci"
      - "dependencies"
    reviewers:
      - "FeelTheFonk"
    groups:
      github-actions:
        patterns:
          - "*"
    ignore:
      - dependency-name: "actions/*"
        update-types: ["version-update:semver-patch"]