name: Release

on:
  push:
    tags:
      - 'v*'  # Déclenche sur les tags commençant par v (ex: v1.0.0)

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Nécessaire pour créer la release
      id-token: write  # Nécessaire pour la publication PyPI
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          
      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build twine
          
      - name: Build package
        run: python -m build
      
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
          generate_release_notes: true
      
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1